In [3]:
import numpy as np

numpy > btkhlena nt3aml maa el data bta3tna ka2nha vectors

In [13]:
v1 = np.array([10,6,7])
v2 = np.array([20,3,3])
v_add = v1 + v2
print(v1)
print(type(v1))
print(v2)
print(v_add)
print(v1.dot(v2))
print(v1.shape) # ht2ol shlk el matrix/vector > de row vector,

[10  6  7]
<class 'numpy.ndarray'>
[20  3  3]
[30  9 10]
239
(3,)


In [17]:
s = np.array(5)
print(s.ndim)
print(s.shape)

0
()


In [12]:
m1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(m1)
print(m1.ndim) #ht2ol hya el array kam dimension
print(m1.shape) #shkl el matrix (acts as a function and an attribute)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [5]:
#bahawel vector to matrix b eny adelo arkam el dimensions fe function esmaha reshape
vec = np.array([1,2,3,4,5,6])
mat = vec.reshape((3,2))
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
#tare2a tanya lel reshaping
vec2 = np.array([1,2,3,4])
vec2.shape[0] #tet3ly number of rows ely aandy w 1 no of columns, tal3t 4
mat2 = vec2.reshape((vec2.shape[0],1))
mat2

array([[1],
       [2],
       [3],
       [4]])

In [13]:
#tare2a talta
vec3 = np.array([1,2,3,4])
mat3 = vec3[:, None]
mat3

array([[1],
       [2],
       [3],
       [4]])

In [22]:
#ntl3 el type of array, fe priority :
#el np.array priority btaato: object > string > float > integer > boolean
matr = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,True]])
matr.dtype

dtype('int64')

HOW DATA IS SEEN IN NP.ARRAY "PRIOTITY" :                                       
object --> string --> float --> integer --> boolean

In [21]:
class C:
    x = 3
c1 = C() #c1 object men class C

matr2 = np.array([[c1, 8],
                  [3,2]])
type(matr2)
mat.dtype

dtype('int64')

In [24]:
#ahawel el type bta3 el array l ay type ana ayzah, hena men int l float
matr3 = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(matr3.dtype)
float_matr3 = matr3.astype(float)
print(float_matr3)

int64
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [26]:
v = np.array([2,4,5,7,8,9])
print(v[2:5])
print(v[-2:-1])

[5 7 8]
[8]
