numpy revision

In [1]:
import numpy as np

In [ ]:
vec = np.array([1,2,3])
vec.dtype   #ytl3 el type bta3 el vector da

dtype('int64')

In [ ]:
#hena shaf kol haga as a string ashan string has a higher priority
mat = np.array([["1",2,3],
                [4,5,6],
                [7,8,9]])
print(mat.dtype)

#priorities: object --> string --> float --> integer --> boolean

<U21


In [ ]:
#aghyr ay data type l a specific data type
fmat = mat.astype(float)
fmat.dtype


dtype('float64')

In [ ]:
#indexing
mat1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(mat1[1,2])
print(mat1[1,-3])


6
4


In [ ]:
#slicing
mat2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9],
                 [0,0,0]])
print(mat2[:]) #aayz kolo
print(mat2[-3:-1, -3:-1]) #aayz goz2 ely in between (intersection)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 0 0]]
[[4 5]
 [7 8]]


In [ ]:
#getting the transpose of a matrix
mat2.T

array([[1, 4, 7, 0],
       [2, 5, 8, 0],
       [3, 6, 9, 0]])

In [20]:
#generate all zeros/all ones matrix of specified dimensions 
mat3 = np.zeros((3,4))
print(mat3)

mat4 = np.ones((3,4))
print(mat4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#function full htemla el matric of a specific size bel value ellana ayzah
mat5 = np.full((3,3), 5)
mat5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [22]:
mat6 = np.empty((3,3))
mat6

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323],
       [3.5e-323, 4.0e-323, 4.4e-323]])

In [24]:
angle = np.arange(0,361,90)
angle

array([  0,  90, 180, 270, 360])

In [ ]:
#identity matrix of a specifc size
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#generating random matrix values for a specifc size
np.random.random((3,3))

array([[0.03247134, 0.20572348, 0.70861632],
       [0.5557992 , 0.23785202, 0.97721859],
       [0.58518203, 0.94754053, 0.66558358]])

In [29]:
#generating random matric values for a specifc size within a specific range (0->10)
np.random.randint(0,11 ,(5,5))

array([[ 9,  3,  4,  9,  5],
       [ 6,  3,  1,  2, 10],
       [ 9,  4,  4, 10,  4],
       [ 4,  4,  4,  8,  8],
       [ 7,  5,  6,  6,  5]], dtype=int32)

In [ ]:
#generating a matric randomly from given data
a= ["JOE", True, 21, "DIDA"]
np.random.choice(a, (3,5))

array([['21', 'True', 'DIDA', 'DIDA', 'DIDA'],
       ['True', 'True', 'DIDA', 'True', 'JOE'],
       ['True', 'JOE', 'JOE', '21', '21']], dtype='<U21')

In [34]:
#saving to file using (savez) w between brackets esm el file
mat7 = np.ones((3,4))
mat8 = np.zeros((5,3))
np.savez('np_file', ones_matrix = mat7, zeros_matrix = mat8)

with np.load('np_file.npz') as file:
    mat7 = file['ones_matrix']
    mat8 = file['zeros_matrix']
    
print(mat7)
print(mat8)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [37]:
def array_reshape(arr, rows = -1, cols = -1):
    try:
        arr = np.array(arr)
        return arr.reshape(rows, cols)
    except (TypeError, ValueError) as e:
        raise ValueError(f"Invalid reshape operation: {e}")
    
vec = [1,2,3,4,5,6]
print(array_reshape(vec,2,3))

[[1 2 3]
 [4 5 6]]


In [39]:
#nlef ala kol el elements nshof law greater than 1 > true or false
v = np.array([1,2,3,4,5,0])
print(np.all(v >= 1))

False


In [ ]:
#bshof how diff are they, atol bthaded close b ad eh
v1 = np.array([1,2,3,4,5])
v2 = np.array([2,3,0,5,3])
print(np.isclose(v1, v2, atol=1))
print(np.allclose(v1, v2, atol=1))

[ True  True False  True False]
False


In [47]:
v3 = np.array([2,4,3,4,10])
condition = v3>= 4
print(condition)


[False  True False  True  True]


In [49]:
v4 = np.array([2,4,3,4,10])
condition = v4>= 4
conditional_access = v4[condition]
print(conditional_access)

[ 4  4 10]


In [50]:
v5 = np.array([2,4,3,4,10])
condition = v5>= 4
new_arr = np.where(condition, -1,v5)
print(new_arr)

[ 2 -1  3 -1 -1]


In [4]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([2,3,0,5,3])

v3 = v1, v2
print(v3)

(array([1, 2, 3, 4, 5]), array([2, 3, 0, 5, 3]))
